name: Build Electron

on: workflow_dispatch

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'
    - name: Install Node.js dependencies
      run: npm install
    - name: Install Electron Forge
      run: npm install --save-dev @electron-forge/cli
    - name: Install Electron Forge (WiX MSI module)
      if: ${{ matrix.os  == 'windows-latest' }}
      run: npm install --save-dev @electron-forge/maker-wix
    - name: Setup Electron Forge
      run: npx electron-forge import
    - name: Build app for macOS/Linux (x86_64)
      if: ${{ matrix.os != 'windows-latest' }}
      run: npx electron-forge make --arch x64
    - name: Build app for Windows (x86_64)
      if: ${{ matrix.os == 'windows-latest' }}
      run: npx electron-forge make --arch x64 --targets @electron-forge/maker-wix
    - name: Upload artifacts (x86_64)
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ matrix.os }}-x86_64
        path: out/make
    - name: Reset artifacts
      run: rm -r out/make
    - name: Build app for macOS/Linux (arm64)
      if: ${{ matrix.os != 'windows-latest' }}
      run: npx electron-forge make --arch arm64
    - name: Build app for Windows (arm64)
      if: ${{ matrix.os == 'windows-latest' }}
      run: npx electron-forge make --arch arm64 --targets @electron-forge/maker-wix
    - name: Upload artifacts (arm64)
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ matrix.os }}-arm64
        path: out/make
    
    
